// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xhtcbcujfusrzvwcmama.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhodGNiY3VqZnVzcnp2d2NtYW1hIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MDMwMTIsImV4cCI6MjA2NDI3OTAxMn0.ELy6g-1omujgfoCHffu6dGg7W1ykYMLhKpnUgCp7Bew";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);